# This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).

module ApimaticCalculatorTestcases
  class APIMATICCalculatorTestcasesClient
    # Singleton access to simple_calculator controller
    # @return [SimpleCalculatorController] Returns the controller instance
    def simple_calculator
      SimpleCalculatorController.instance
    end

    # Initializer with authentication and configuration parameters
    def initialize(basic_auth_user_name: nil, basic_auth_password: nil)
      Configuration.basic_auth_user_name = basic_auth_user_name
      Configuration.basic_auth_password = basic_auth_password
    end
  end
end
