# This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).

module ApimaticCalculatorTestcases
  class Configuration
    # The base Uri for API calls
    @base_uri = 'http://examples.apimatic.io/apps/calculator'

    # The username to use with basic authentication
    @basic_auth_user_name = 'TODO: Replace'

    # The password to use with basic authentication
    @basic_auth_password = 'TODO: Replace'

    # create the getters and setters
    class << self
      attr_accessor :base_uri
      attr_accessor :basic_auth_user_name
      attr_accessor :basic_auth_password
    end
  end
end
