# This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
require 'openssl'
require 'json'
require 'unirest'

# APIMATIC Helper Files
require_relative 'apimatic_calculator_testcases/api_helper.rb'
require_relative 'apimatic_calculator_testcases/configuration.rb'
require_relative 'apimatic_calculator_testcases/apimatic_calculator_testcases_client.rb'

# Http
require_relative 'apimatic_calculator_testcases/http/http_call_back.rb'
require_relative 'apimatic_calculator_testcases/http/http_client.rb'
require_relative 'apimatic_calculator_testcases/http/http_method_enum.rb'
require_relative 'apimatic_calculator_testcases/http/http_request.rb'
require_relative 'apimatic_calculator_testcases/http/http_response.rb'
require_relative 'apimatic_calculator_testcases/http/http_context.rb'
require_relative 'apimatic_calculator_testcases/http/unirest_client.rb'

# Models
require_relative 'apimatic_calculator_testcases/models/operation_type_enum.rb'

# Exceptions
require_relative 'apimatic_calculator_testcases/exceptions/api_exception.rb'

# Controllers
require_relative 'apimatic_calculator_testcases/controllers/base_controller.rb'
require_relative 'apimatic_calculator_testcases/controllers/simple_calculator_controller.rb'
